### PR TITLE
Added device 006-200 (air conditioner)

### PR DESCRIPTION
**Pull request by Go2Engle**
This device seems to be the same as device 006-201. Everything seems to be working fine with my Portable air conditioner.

### CODE REVIEW

**Comment by Go2Engle** [comment]
@oyvindwe maybe you can point me in the right direction. the above works fine other then I would like to remove the auto and heat hvac_modes as they dont exist on this portable AC. You can see in my previous 2 commits what i tried but that doesnt seem to work correctly?

**Comment by oyvindwe** [comment]
Thank you for your contribution ❤️ 

Note that there is already an open PR for 006-200: PR #97 

When I uncomment `4: auto` for another climate device (009-106), the auto mode does disappear for me. Not that you have to restart HA after editing the mapping.

If you provide a JSON dump (see https://github.com/oyvindwe/connectlife), I can help testing the mappings.

**Comment by Go2Engle** [comment]
So I tried removing both auto and heat as this unit does not have heat and i tried leaving the others as the numbers they were originally set too and also tried re numbering 0,1,2,3 and both seemed to cause issues. I did reboot each time I made changes but maybe an issue on my end? Which would be the appropriate way?

Also below is json dump below.

```json
{
  "bindTime": 1657480168623,
  "createTime": 0,
  "deviceFeatureCode": "200",
  "deviceFeatureName": "200\u5355\u51b7\u673a\u578b\u65e0\u529f\u7387",
  "deviceId": "<redacted>",
  "deviceNickName": "chilly",
  "deviceTypeCode": "006",
  "deviceTypeName": "",
  "offlineState": 1,
  "puid": "<redacted>",
  "role": 1,
  "roomId": 591103,
  "roomName": "master bedroom",
  "seq": 0,
  "statusList": {
    "daily_energy_kwh": 0,
    "f-filter": "0",
    "f_e_arkgrille": "0",
    "f_e_dwmachine": "0",
    "f_e_incoiltemp": "0",
    "f_e_incom": "0",
    "f_e_indisplay": "0",
    "f_e_ineeprom": "0",
    "f_e_inele": "0",
    "f_e_infanmotor": "0",
    "f_e_inhumidity": "0",
    "f_e_inkeys": "0",
    "f_e_intemp": "0",
    "f_e_invzero": "0",
    "f_e_inwifi": "0",
    "f_e_outcoiltemp": "0",
    "f_e_outeeprom": "0",
    "f_e_outgastemp": "0",
    "f_e_outtemp": "0",
    "f_e_over_cold": "0",
    "f_e_over_hot": "0",
    "f_e_push": "0",
    "f_e_upmachine": "0",
    "f_e_waterfull": "0",
    "f_ecm": "0",
    "f_electricity": "0",
    "f_humidity": "128",
    "f_temp_in": "73",
    "f_votage": "0",
    "t_dal": "0",
    "t_demand_response": "0",
    "t_eco": "0",
    "t_fan_mute": "0",
    "t_fan_speed": "0",
    "t_fan_speed_s": "0",
    "t_fanspeedcv": "0",
    "t_power": "1",
    "t_sleep": "0",
    "t_super": "0",
    "t_swing_angle": "0",
    "t_swing_direction": "0",
    "t_swing_follow": "0",
    "t_talr": "0",
    "t_temp": "72",
    "t_temp_compensate": "6",
    "t_temp_type": "1",
    "t_tms": "0",
    "t_up_down": "0",
    "t_work_mode": "2"
  },
  "useTime": 0,
  "wifiId": "<redacted>"
}

**Comment by smaddock** [comment]
Trying to be helpful and not just open a third pull request...
- this is my JSON dump: https://gist.github.com/smaddock/d68e4b4f61deaa36bce7454610f3d0a6
- this is the data dictionary I've been using for a few weeks now successfully: https://gist.github.com/smaddock/d0a36e6d15b4cf0b36265ce2c03bb1c6

Note that my device does not have heat but the ConnectLife app does show an auto option, so I left that.

**Comment by Go2Engle** [comment]
> Trying to be helpful and not just open a third pull request...
> 
>     * this is my JSON dump: https://gist.github.com/smaddock/d68e4b4f61deaa36bce7454610f3d0a6
> 
>     * this is the data dictionary I've been using for a few weeks now successfully: https://gist.github.com/smaddock/d0a36e6d15b4cf0b36265ce2c03bb1c6
> 
> 
> Note that my device does not have heat but the ConnectLife app does show an auto option, so I left that.

ahhh this is perfect! and yup your right it does have auto! somehow I missed that when looking in connectlife. will update my PR now.

**Review by oyvindwe — APPROVED** [review]

**Pull request merged**
