### PR TITLE
Data dictionary for refridgerator 026-1b0610z0049j (BCD-610WP1BWF1S3/HC4(HAB))

### PR DESCRIPTION
**Pull request by oyvindwe**

### CODE REVIEW

**Comment by oyvindwe** [comment]
@deb0ro I have started on your fridge, but it has _a lot_ of properties.

I'm happy to get input on the mappings:
- Properties can we disable long-term statistic for
- Properties to show by default
- Properties that are settable, and their values and labels (use the ConnectLife app to set properties and compare values in Home Assistant)
- Units for properties

**Comment by deb0ro** [comment]
Screenshot_20240712_082547

Hi, this is the screenshot of settings available in ConnectLife app. You can set temperature for freezer and fridge and turn on "super" features, ice making machine and eco mode. Thats basically it. There is also a self diag (but I think its just a dummy progress bar 😃) and interesting statistics about how many the doors were opened per day/week/month.

As you said, there is a lot of properties but like 70% of them are just there from different models I would say. Like: camera_state, wine_*, rgb_*...if we filter out all 0 values, the list should be much thinner.

**Comment by oyvindwe** [comment]
@deb0ro Thank you very much! Could you provide a screenshot of the "Usage Frequency Metrics" page as well?

**Comment by deb0ro** [comment]
Sure, here you go 😉

Screenshot_20240712_163952
Screenshot_20240712_164011

**Comment by oyvindwe** [comment]
Thanks. I agree that's not very useful, but HA can probably provide the same by figuring out which property they are tracking.

**Comment by oyvindwe** [comment]
I guessed a bit if those temperature settings can be set or not - I'm not sure what the "variation temperature" is.
Also it looks like they need some sensible min and max values.

These are the controls I have mapped:
image

Sample card:
image

If you think it looks OK, I'm happy to merge and make a release. We can always improve on the mappings later!

**Comment by oyvindwe** [comment]
Note: I have not been able to figure out mappings for "Super cool", "Super freeze" and "Eco". If you change those settings in the API, which properties are changes in Home Assistant?

**Pull request merged**
